
############## EXAMPLES #################
# mage install
# mage release
# bump= mage release // will increase version
# names=one,two mage release | install

###### Build

build_tags=""

###### Clean

to_clean_dirs=["PREP/","cross"]

###### APPS

md5Exe="/usr/local/bin/md5sum"
sha1Exe="/usr/local/bin/sha1sum"
sha256Exe="/usr/local/bin/sha256sum"
curlExe="/usr/bin/curl"
catExe="/bin/cat"
gitExe="/usr/local/bin/git"
tarExe="/usr/bin/tar"
scpExe="/usr/bin/scp"
sftpExe="/usr/bin/sftp"
upxExe="/usr/local/bin/upx"
whichExe="/usr/bin/which"

###### Deployment

# host must be available via ping check, requires ppk setup
#[[scp]]
#host="192.168.1.11"
#path="main:/apps/"

#[[sftp]]
#host="gfcollin@myserver"
#path="/apps/"
#skip_ping="true"

# host must be available via http check
#[[artifactory]]
#host="192.168.1.11"
#path="http://192.168.1.11:8081/artifactory/go-release-local/mailer/"
#creds="/Users/username/auths/.myartifactorycreds"

###### Project Properties

[[application]]
name="gauth"
ostargets=["darwin/amd64"]
osdeployscripts=["./pkgr/deploy_darwin.sh"]
package="github.com/gcstang/gauth"
version="VERSION.txt"
readme="README.md"
changelog="CHANGES.txt"
files=["./pkgr/bash_autocomplete","README.md"]
